flags: {}
extra-package-dbs: []
packages:
- Game
- Web
system-ghc: false
extra-deps:
- bifunctors-5.4.1
- bytestring-builder-0.10.8.1.0
- comonad-5
- kan-extensions-5.0.1
- lens-4.14
- semigroupoids-5.1
- transformers-compat-0.5.1.4
- warp-3.2.8
resolver: lts-6.10
